display:
    numberOfDecimals: 2
worldConfig:
    groups:
        default:
            config:
                basePrice: 2.5
                minPricePerStack: 0.1
                sellPriceSteepness: 0.03
                buyPriceSteepness: 0.03
                buyPriceAsymptoteSlope: 0.02
                sellPriceFactor: 1.0
                buyPriceFactor: 1.0
                saleDecayPerDay: 0.01
                buyDecayPerDay: 0.1
        survivalGroup:
            worlds:
            - world
            - world_nether
            - world_the_end
